service:
  name: serverless-boilerplate

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  scheduleEnabled:
    production: true
    dev: false
    local: false

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB

  environment:
    DELETE_ME: Env variable
  logs:
    httpApi: true

functions:
  getExample:
    handler: src/handlers/get.getExample
    events:
      - http:
          path: getExample
          method: get
          cors: true
